### ISSUE TITLE
What interactive events could be interesting to feature at LDW23?

### ISSUE THREAD

**Issue by londondataweek** [londondataweek/ldw23#1]

**Comment by dingaaling** [comment]
- The ODI has a Data Board Game
- [Cabaret of Dangerous Ideas](https://www.cabaretofdangerousideas.com/) introduces complex concepts using comedy
- Public debates could take the form of [Intelligence Squared](https://intelligencesquared.com/) style dialogue where people vote to show how their ideas have/haven't changed OR a debate where there are 2 empty seats and audience members can join 
- Live AI demo/competition could be interesting liked [this](https://twitter.com/alexabruck/status/1587108608482869251) but should be aware/address the bias/flaws of this tech
